### PR TITLE
Bump github.com/lestrrat-go/jwx to v2.

### PR DESCRIPTION
**Pull request by jas4711**
Hi!

Your minio/pkg is packaged and is planned to be part of the next Debian release: https://tracker.debian.org/pkg/golang-github-minio-pkg

We also have a package for github.com/lestrrat-go/jwx however that is stuck on v1 because of minio/pkg relies on v1.  

Would you consider upgrading minio/pkg to the v2 branch?

This would help us to package other tools (for example, buildkite) that uses the v2 branch of github.com/lestrrat-go/jwx without having to support both packages for v1 and v2 in Debian.  As I'm not familiar with the code here, this pull request is just the core `go get github.com/lestrrat-go/jwx/v2@v2.1.2` but likely some more changes are needed to use the v2 branch.

It seems upstream lestrrat-go/jwx recommends using v2 or v3 branches, and the v1 is deprecated.

Thanks,
Simon

### CODE REVIEW

**Comment by gibmat** [comment]
The necessary code changes for switching to v2 seem pretty straightforward. Referencing https://github.com/lestrrat-go/jwx/blob/v2/Changes-v2.md and https://github.com/lestrrat-go/jwx/blob/v2/examples/jwt_example_test.go#L83, this seems sufficient:

```
diff --git a/env/web_env.go b/env/web_env.go
index c1832bb..5829326 100644
--- a/env/web_env.go
+++ b/env/web_env.go
@@ -100,7 +100,7 @@ func getEnvValueFromHTTP(urlStr, envKey string) (string, string, string, error)
                return "", "", "", err
        }
 
-       skey, err := jwk.New([]byte(password))
+       skey, err := jwk.FromRaw([]byte(password))
        if err != nil {
                return "", "", "", err
        }
@@ -119,7 +119,7 @@ func getEnvValueFromHTTP(urlStr, envKey string) (string, string, string, error)
                return "", "", "", err
        }
 
-       signed, err := jwt.Sign(token, jwa.HS512, skey)
+       signed, err := jwt.Sign(token, jwt.WithKey(jwa.HS512, skey))
        if err != nil {
                return "", "", "", err
        }
diff --git a/licverifier/verifier.go b/licverifier/verifier.go
index 1233181..7813194 100644
--- a/licverifier/verifier.go
+++ b/licverifier/verifier.go
@@ -29,6 +29,7 @@ import (
 
        "github.com/lestrrat-go/jwx/jwa"
        "github.com/lestrrat-go/jwx/jwk"
+       "github.com/lestrrat-go/jwx/jws"
        "github.com/lestrrat-go/jwx/jwt"
 )
 
@@ -102,13 +103,13 @@ func NewLicenseVerifier(pemBytes []byte) (*LicenseVerifier, error) {
        if err != nil {
                return nil, fmt.Errorf("Failed to parse public key: %s", err)
        }
-       key, err := jwk.New(pbKey)
+       key, err := jwk.FromRaw(pbKey)
        if err != nil {
                return nil, err
        }
        key.Set(jwk.AlgorithmKey, jwa.ES384)
        keyset := jwk.NewSet()
-       keyset.Add(key)
+       keyset.AddKey(key)
        return &LicenseVerifier{
                keySet: keyset,
        }, nil
@@ -176,7 +177,7 @@ func toLicenseInfo(license string, token jwt.Token) (LicenseInfo, error) {
 
 // Verify verifies the license key and validates the claims present in it.
 func (lv *LicenseVerifier) Verify(license string, options ...jwt.ParseOption) (LicenseInfo, error) {
-       options = append(options, jwt.WithKeySet(lv.keySet), jwt.UseDefaultKey(true), jwt.WithValidate(true))
+       options = append(options, jwt.WithKeySet(lv.keySet, jws.WithUseDefault(true)), jwt.WithValidate(true))
        token, err := jwt.ParseString(license, options...)
        if err != nil {
                return LicenseInfo{}, fmt.Errorf("failed to verify license: %s", err)
```

**Comment by jas4711** [comment]
Thank you @gibmat - I have added the patch to the pull request.  Maybe GitHub Actions will be happier now, I'm not that familiar with this...

**Comment by harshavardhana** [comment]
Will fix it locally.

**Comment by harshavardhana** [comment]
this is done in fe7fc288ebc648f90a9ace8c14387bcce9d99903

**Pull request closed without merging**
